# -*- coding: utf-8 -*-
"""golen_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uyHQvJMFIyIM8pllvGyrqudkedERiHSJ

HS-DAQ MAC Array - Python Golden Model
========================================
Spec:
  Input feature map bit-width : 12 bit  (unsigned) - biosignal sample, matches
                                 HS-DAQ RTL's ADC_WIDTH parameter exactly
  Weight bit-width            :  8 bit  (signed)   - pre-trained anomaly pattern coefficient
  Output bit-width            : 32 bit  (signed)   - accumulated anomaly score

  MAC array size (physical)   : 8 x 4   (= NUM_CHANNELS x WINDOW_SIZE, matches
                                 HS-DAQ RTL's NUM_CHANNELS parameter exactly)

  Input feature map matrix    : 8 x 4   (8 channels x 4-sample sliding window)
  Weight matrix               : 8 x 4   (per-channel anomaly pattern weight)
  Output feature map matrix   : 8 x 1   (per-channel anomaly score)

  Operation: per-channel dot product (NOT full matrix multiply, NOT systolic --
  each channel's 4-tap window is independent, so a simple parallel MAC bank
  is used; there is no data reuse between channels that would justify the
  added pipeline latency / wiring complexity of a systolic array)
    output[ch] = sum_{k=0}^{3} input[ch][k] * weight[ch][k]

  NOTE on input range: adc_data in HS-DAQ RTL is unsigned 12-bit (0..4095),
  the raw output of the ADC. It is NOT sign-extended when packed into the
  MAC array's input -- it is zero-extended, since it is genuinely an
  unsigned quantity. Internally we still carry it as a signed 13-bit value
  (12-bit magnitude + 1 guard bit = 0) purely so the multiply below can use
  a uniform signed multiplier shared with the (signed) weight input.
"""

import numpy as np

NUM_CHANNELS = 8
WINDOW_SIZE  = 4
N_TESTS      = 1000

INPUT_MIN, INPUT_MAX   = 0, 4095          # unsigned 12-bit (actual ADC range)
WEIGHT_MIN, WEIGHT_MAX = -128, 127        # INT8


def mac_per_channel(input_fm: np.ndarray, weight: np.ndarray) -> np.ndarray:
    """
    input_fm: (8, 4) unsigned 12-bit (stored as int32 in [0, 4095])
    weight:   (8, 4) INT8
    returns:  (8,)   INT32  -- per-channel dot product
    """
    input_fm = np.clip(input_fm, INPUT_MIN, INPUT_MAX).astype(np.int32)  # unsigned, but int32 container is fine for the math
    weight   = np.clip(weight, WEIGHT_MIN, WEIGHT_MAX).astype(np.int8)

    output = np.zeros(NUM_CHANNELS, dtype=np.int64)  # int64 intermediate to avoid numpy overflow during accumulation
    for ch in range(NUM_CHANNELS):
        acc = 0
        for k in range(WINDOW_SIZE):
            acc += int(input_fm[ch][k]) * int(weight[ch][k])
        output[ch] = acc

    return output.astype(np.int32)


def overflow_check():
    """Verify INT32 accumulator is safe for the worst-case input."""
    # input is unsigned [0,4095]; worst case product magnitude is at INPUT_MAX
    # paired with the most negative weight (most negative product) or
    # INPUT_MAX paired with WEIGHT_MAX (most positive product).
    max_single_product = INPUT_MAX * WEIGHT_MAX           # 4095 * 127
    min_single_product = INPUT_MAX * WEIGHT_MIN            # 4095 * -128 (most negative, since input >= 0)
    max_acc = max_single_product * WINDOW_SIZE
    min_acc = min_single_product * WINDOW_SIZE

    INT32_MIN, INT32_MAX = -2_147_483_648, 2_147_483_647

    print("=== Overflow check ===")
    print(f"max single product : {max_single_product:>12,}")
    print(f"min single product : {min_single_product:>12,}")
    print(f"max accumulated ({WINDOW_SIZE} terms): {max_acc:>12,}")
    print(f"min accumulated ({WINDOW_SIZE} terms): {min_acc:>12,}")
    print(f"INT32 range: [{INT32_MIN:,}, {INT32_MAX:,}]")
    safe = (INT32_MIN <= min_acc) and (max_acc <= INT32_MAX)
    print(f"INT32 accumulator safe? {safe}")
    print()
    assert safe, "INT32 accumulator overflow risk"


def generate_test_vectors(seed: int = 42):
    """Generate N_TESTS random (input, weight) pairs and compute golden outputs."""
    rng = np.random.default_rng(seed)

    # input: unsigned 12-bit, [0, 4095] -- matches HS-DAQ adc_data range exactly
    inputs  = rng.integers(INPUT_MIN, INPUT_MAX + 1, size=(N_TESTS, NUM_CHANNELS, WINDOW_SIZE), dtype=np.int32)
    weights = rng.integers(WEIGHT_MIN, WEIGHT_MAX + 1, size=(N_TESTS, NUM_CHANNELS, WINDOW_SIZE), dtype=np.int32).astype(np.int8)

    goldens = np.zeros((N_TESTS, NUM_CHANNELS), dtype=np.int32)
    for n in range(N_TESTS):
        goldens[n] = mac_per_channel(inputs[n], weights[n])

    return inputs, weights, goldens


def write_hex_files(inputs, weights, goldens):
    """
    Write flat hex files for $readmemh in the RTL testbench.
    Order: test 0 [ch0_k0, ch0_k1, ch0_k2, ch0_k3, ch1_k0, ...] test 1 [...] ...
    """
    with open("test_input.hex", "w") as f:
        for n in range(N_TESTS):
            for ch in range(NUM_CHANNELS):
                for k in range(WINDOW_SIZE):
                    val = int(inputs[n][ch][k]) & 0xFFF  # unsigned 12bit -> 3 hex digits
                    f.write(f"{val:03X}\n")

    with open("test_weight.hex", "w") as f:
        for n in range(N_TESTS):
            for ch in range(NUM_CHANNELS):
                for k in range(WINDOW_SIZE):
                    val = int(weights[n][ch][k]) & 0xFF  # INT8 -> 2 hex digits
                    f.write(f"{val:02X}\n")

    with open("golden.hex", "w") as f:
        for n in range(N_TESTS):
            for ch in range(NUM_CHANNELS):
                val = int(goldens[n][ch]) & 0xFFFFFFFF  # INT32 -> 8 hex digits
                f.write(f"{val:08X}\n")

    print(f"Wrote test_input.hex  ({N_TESTS * NUM_CHANNELS * WINDOW_SIZE} lines, unsigned 12-bit)")
    print(f"Wrote test_weight.hex ({N_TESTS * NUM_CHANNELS * WINDOW_SIZE} lines, INT8)")
    print(f"Wrote golden.hex      ({N_TESTS * NUM_CHANNELS} lines, INT32)")


def compare_with_rtl(rtl_output_file: str = "rtl_out.hex"):
    """Compare RTL simulation output against golden.hex (run after vsim finishes)."""
    with open("golden.hex") as g, open(rtl_output_file) as r:
        golden_lines = [l.strip() for l in g.readlines()]
        rtl_lines    = [l.strip() for l in r.readlines()]

    if len(golden_lines) != len(rtl_lines):
        print(f"WARNING: line count mismatch (golden={len(golden_lines)}, rtl={len(rtl_lines)})")

    mismatches = 0
    for idx, (g_line, r_line) in enumerate(zip(golden_lines, rtl_lines)):
        g_val = int(g_line, 16)
        r_val = int(r_line, 16)
        if g_val != r_val:
            test_n = idx // NUM_CHANNELS
            ch     = idx % NUM_CHANNELS
            print(f"MISMATCH test={test_n} ch={ch}: golden={g_val:#010x} rtl={r_val:#010x}")
            mismatches += 1

    print(f"\nTotal mismatches: {mismatches} / {len(golden_lines)}")
    if mismatches == 0:
        print("ALL TESTS PASSED")


if __name__ == "__main__":
    overflow_check()
    inputs, weights, goldens = generate_test_vectors(seed=42)
    write_hex_files(inputs, weights, goldens)

    # Sanity check on first test case
    print("\n=== Sanity check (test 0) ===")
    print("input[0] (ch0, 4 samples):", inputs[0][0])
    print("weight[0] (ch0, 4 samples):", weights[0][0])
    print("golden[0] (8 channels):", goldens[0])