// =============================================================================
// tb_mac_array.sv
// Compares mac_array RTL output against Python golden model (golden.hex)
// over N_TESTS random vectors.
// Requires test_input.hex, test_weight.hex, golden.hex (generated by
// golden_model.py) to be present in the simulation working directory.
// =============================================================================
`timescale 1ns/1ps

module tb_mac_array;

    localparam NUM_CHANNELS = 8;
    localparam WINDOW_SIZE  = 4;
    localparam IN_WIDTH     = 12;   // unsigned, matches ADC_WIDTH
    localparam W_WIDTH      = 8;
    localparam OUT_WIDTH    = 32;
    localparam N_TESTS      = 1000;

    logic clk = 0;
    logic rst_n=0;
    always #5 clk = ~clk; // 100MHz

    logic        [IN_WIDTH-1:0] input_fm [0:NUM_CHANNELS-1][0:WINDOW_SIZE-1];  // unsigned
    logic signed [W_WIDTH-1:0]  weight   [0:NUM_CHANNELS-1][0:WINDOW_SIZE-1];
    logic                       valid_in;

    logic signed [OUT_WIDTH-1:0] result [0:NUM_CHANNELS-1];
    logic                        valid_out;

    mac_array #(
        .NUM_CHANNELS(NUM_CHANNELS),
        .WINDOW_SIZE(WINDOW_SIZE),
        .IN_WIDTH(IN_WIDTH),
        .W_WIDTH(W_WIDTH),
        .OUT_WIDTH(OUT_WIDTH)
    ) dut (
        .clk(clk), .rst_n(rst_n),
        .input_fm(input_fm), .weight(weight), .valid_in(valid_in),
        .result(result), .valid_out(valid_out)
    );

    // -------------------------------------------------------------------
    // Load Python-generated test vectors
    // -------------------------------------------------------------------
    // Flat arrays: test_input.hex / test_weight.hex are written in order
    // [test][channel][window_tap], golden.hex in order [test][channel].
    logic [IN_WIDTH-1:0] test_input  [0:N_TESTS*NUM_CHANNELS*WINDOW_SIZE-1];
    logic [W_WIDTH-1:0]  test_weight [0:N_TESTS*NUM_CHANNELS*WINDOW_SIZE-1];
    logic [OUT_WIDTH-1:0] golden     [0:N_TESTS*NUM_CHANNELS-1];

    int mismatch_count = 0;
    int total_checks   = 0;
    integer out_file;

    initial begin
		$readmemh("C:/intelFPGA_lite/18.1/HSDAQ/test_input.hex",  test_input); //local direction
		$readmemh("C:/intelFPGA_lite/18.1/HSDAQ/test_weight.hex", test_weight); //local direction
		$readmemh("C:/intelFPGA_lite/18.1/HSDAQ/golden.hex",      golden); //local direction

		out_file = $fopen("C:/intelFPGA_lite/18.1/HSDAQ/rtl_out.hex", "w"); //local direction

        rst_n = 0;
        valid_in = 0;
        repeat (3) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        for (int n = 0; n < N_TESTS; n++) begin
            // Load this test's 8x4 input/weight matrices
            for (int ch = 0; ch < NUM_CHANNELS; ch++) begin
                for (int k = 0; k < WINDOW_SIZE; k++) begin
                    automatic int flat_idx = n*NUM_CHANNELS*WINDOW_SIZE + ch*WINDOW_SIZE + k;
                    input_fm[ch][k] = test_input[flat_idx];  // unsigned, no sign extension
                    weight[ch][k]   = $signed(test_weight[flat_idx]);
                end
            end

            // 1-cycle valid_in pulse -- mac_array latches the matrix
            // internally and sequences all 4 taps on its own.
            valid_in = 1;
            @(posedge clk);
            valid_in = 0;

            // Wait for the array to finish its internal 4-tap sequence
            @(posedge valid_out);
            #1; // settle after nonblocking updates

            // Compare each channel's result against golden
            for (int ch = 0; ch < NUM_CHANNELS; ch++) begin
                automatic int golden_idx = n*NUM_CHANNELS + ch;
                logic signed [OUT_WIDTH-1:0] expected;
                expected = $signed(golden[golden_idx]);

                $fwrite(out_file, "%08X\n", result[ch] & {OUT_WIDTH{1'b1}});

                total_checks++;
                if (result[ch] !== expected) begin
                    $display("[MISMATCH] test=%0d ch=%0d got=%0d expected=%0d",
                             n, ch, result[ch], expected);
                    mismatch_count++;
                end
            end
        end

        $fclose(out_file);

        $display("==============================================");
        $display("MAC array test: checks=%0d mismatches=%0d", total_checks, mismatch_count);
        if (mismatch_count == 0)
            $display("MAC ARRAY TEST PASSED (%0d/%0d test vectors, 0 mismatches)", N_TESTS, N_TESTS);
        else
            $display("MAC ARRAY TEST FAILED");
        $display("==============================================");

	#100
        $stop;
    end

endmodule
